// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2515.frc2018robot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.drive.MecanumDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainLeftFrontMotor;
    public static SpeedController driveTrainRightFrontMotor;
    public static SpeedController driveTrainLeftRearMotor;
    public static SpeedController driveTrainRightRearMotor;
    public static MecanumDrive driveTrainRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLeftFrontMotor = new Spark(1);
        LiveWindow.addActuator("DriveTrain", "Left Front Motor", (Spark) driveTrainLeftFrontMotor);
        driveTrainLeftFrontMotor.setInverted(false);
        driveTrainRightFrontMotor = new Spark(2);
        LiveWindow.addActuator("DriveTrain", "Right Front Motor", (Spark) driveTrainRightFrontMotor);
        driveTrainRightFrontMotor.setInverted(false);
        driveTrainLeftRearMotor = new Spark(3);
        LiveWindow.addActuator("DriveTrain", "Left Rear Motor", (Spark) driveTrainLeftRearMotor);
        driveTrainLeftRearMotor.setInverted(false);
        driveTrainRightRearMotor = new Spark(4);
        LiveWindow.addActuator("DriveTrain", "Right Rear Motor", (Spark) driveTrainRightRearMotor);
        driveTrainRightRearMotor.setInverted(false);
        driveTrainRobotDrive = new MecanumDrive(driveTrainLeftFrontMotor, driveTrainLeftRearMotor,
              driveTrainRightFrontMotor, driveTrainRightRearMotor);
        LiveWindow.addActuator("DriveTrain", "Robot Drive", driveTrainRobotDrive);
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setMaxOutput(1.0);


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
